services:
    backend:
        build: ./backend
        ports:
            - '5001:5000'
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/job-hunter
            - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
            - NODE_ENV=development
        depends_on:
            - mongodb
        # volumes:
        #     - ./backend:/app
        #     - /app/node_modules

    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:5000
        # volumes:
        #     - ./frontend:/app
        #     - /app/node_modules
        depends_on:
            - backend

    mongodb:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db

    mongo-express:
        image: mongo-express:latest
        ports:
            - '8081:8081'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ADMINUSERNAME=
            - ME_CONFIG_MONGODB_ADMINPASSWORD=
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin123
        depends_on:
            - mongodb

volumes:
    mongodb_data:
